version: '3'
services:
  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd1!
    networks:
    - "store"
    volumes:
      - "mssqlsystem:/var/opt/mssql"
      - "mssqluser:/var/opt/sqlserver"
    restart: always
  store_api:
    container_name: store_api
    image: andriydocker24/online_store_api
    ports:
      - "8000:8080"
      - "7061:8080"
    networks:
    - "store"
    restart: always
networks:
  store:
    driver: bridge
volumes:
  mssqlsystem:
    external: true
  mssqluser:
    external: true